name: scissors_mirroring_example
version: 0.6.7
dependencies:
  angular2: 2.0.0-beta.12
  browser: 0.10.0
dev_dependencies:
  scissors: ^0.6.7
  dart_to_js_script_rewriter: ^0.1.0
transformers:
# Use css_mirroring_transformer as standalone.
- scissors/css_mirroring_transformer:
    verbose: true
- angular2/transform/codegen
- angular2/transform/reflection_remover:
    $include: [web/main.dart]
- dart_to_js_script_rewriter

# Do not use this line in your projects: this is just to use the enclosing
# version of Scissors:
dependency_overrides: {scissors: {path: ../..}}
