name: 'image_compiler'
version: 0.0.1
description: Usage example for image_dart_compiler

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'

dev_dependencies:
  dart_to_js_script_rewriter: '^1.0.1'
  scissors: ^0.6.3+1

transformers:
- scissors/image_dart_transformer:
    $include: "web/pics"
- dart_to_js_script_rewriter

dependency_overrides: {scissors: {path: ../..}}
